# ========== Site Settings ==========
title       : "Yangle Liu | Computing Science"
description : "Developing data-driven methods in ML and CV for forecasting, 3D perception, and intelligent systems."
repository  : "yangleliu/yangleliu.github.io"   # <- 如果仓库名与账户同名（user site），这里填 <username>/<username>.github.io
google_scholar_stats_use_cdn : true

# 可选：Google Analytics
google_analytics_id: "G-HCNJ45760K"

# ========== SEO ==========
google_site_verification:
bing_site_verification:
baidu_site_verification:

# ========== Site Author ==========
author:
  name          : "Yangle Liu"
  avatar        : "images/photo.png"     # 放一张头像到 /images/avatar.jpg（正方形）
  bio           : "BSc Computing Science, University of Liverpool"
  location      : "Liverpool, UK"
  employer      :
  pubmed        :
  googlescholar : "https://scholar.google.com/citations?user=1XMwUH4AAAAJ&hl=en"  # 以后有 Scholar ID 再填
  email         : "2639174816@protonmail.com"
  researchgate  :
  uri           :
  bitbucket     :
  codepen       :
  dribbble      :
  flickr        :
  facebook      :
  foursquare    :
  github        : "Cola-1"             # 你的 GitHub 用户名（若不同请改）
  google_plus   :
  keybase       :
  instagram     :
  impactstory   :
  lastfm        :
  linkedin      :                          # 只填用户名/slug（例如: yangle-liu）
  dblp          :
  orcid         :
  pinterest     :
  soundcloud    :
  stackoverflow :
  steam         :
  tumblr        :
  twitter       :
  vine          :
  weibo         :
  xing          :
  youtube       :
  wikipedia     :

# ========== Reading Files ==========
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README
  - vendor
  - node_modules
  - package.json
  - package-lock.json

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
paginate: 10
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# ========== Markdown ==========
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# ========== Defaults ==========
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# ========== Sass ==========
sass:
  sass_dir: _sass
  style: compressed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# ========== HTML Compression ==========
compress_html:
  clippings: all
  ignore:
    envs: []
